"""The default AutoMix rhythm analyzer: Beat This! run by ONNX Runtime, no PyTorch.

The light librosa analyzer (basic.py) tracks the wrong metrical level on much
real pop: on ~30 tracks its beats agreed with Beat This! at F 0.64 and its
provisional downbeats at 0.26, with double/half/4:3 tempo grids in most songs
-- beat-matched transitions then line one track's beat up with the other's
off-beat. Beat This! itself fixes that, but PyTorch made the installer ~1 GB.

So the installer ships the same ``final0`` network exported to ONNX and
int8-quantized (models/beat_this_final0_int8.onnx, ~21 MB, regenerated by
tools/export_automix_onnx.py) plus ``onnxruntime``. Against the PyTorch
model it reproduces beats at F 0.997 and downbeats at 0.995 on the same
tracks. The log-mel frontend (librosa) matches beat_this.preprocessing.LogMelSpect
to 4e-5, and chunking/peak picking mirror beat_this.inference and
Postprocessor(type="minimal") -- see those for the reference behavior.

Vocal activity comes from Open-Unmix, also ONNX (see vocals.OnnxVocalDetector).
Everything else (bpm/meter confidence, the basic fields, degrading to the
basic result on any inference error, "-novocals" when vocal detection fails)
is BeatThisAnalysisProvider's.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import numpy as np

from app.automix.analysis.beat_this import BeatThisAnalysisProvider
from app.automix.analysis.vocals import ONNX_ENGINE_ID, ONNX_MODEL_NAME, OnnxVocalDetector

MODEL_NAME = "beat_this_final0_int8.onnx"
BUNDLED_MODELS = Path("app") / "automix" / "analysis" / "models"
"""Where playlist_canvas.spec puts the models inside the frozen app (the source tree's layout)."""

SAMPLE_RATE = 22050
N_FFT = 1024
HOP = 441
"""50 frames per second, the rate the network was trained on."""
FPS = 50
CHUNK_FRAMES = 1500
BORDER_FRAMES = 6
PEAK_WINDOW_FRAMES = 7
"""A peak is the maximum within +-70 ms (beat_this Postprocessor "minimal")."""


def model_path(name: str = MODEL_NAME) -> Path:
    bundle = getattr(sys, "_MEIPASS", None)
    return (Path(bundle) / BUNDLED_MODELS if bundle else Path(__file__).with_name("models")) / name


def onnx_beats_available() -> bool:
    """Whether onnxruntime is installed and the model file is present (never imports onnxruntime)."""
    return importlib.util.find_spec("onnxruntime") is not None and model_path().is_file()


def log_mel(signal: np.ndarray) -> np.ndarray:
    """(frames, 128) log-mel spectrogram of a mono 22050 Hz signal, as the network expects."""
    import librosa

    magnitude = np.abs(librosa.stft(signal, n_fft=N_FFT, hop_length=HOP, window="hann",
                                    center=True, pad_mode="reflect")) / np.sqrt(N_FFT)
    bank = librosa.filters.mel(sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=128, fmin=30, fmax=11000, htk=False, norm=None)
    return np.log1p(1000.0 * (bank @ magnitude)).T.astype(np.float32)


def chunk_starts(frames: int) -> list[int]:
    """Chunk starts overlapping by the border the network was not trained on; the last one ends the piece."""
    starts = list(range(-BORDER_FRAMES, frames - BORDER_FRAMES, CHUNK_FRAMES - 2 * BORDER_FRAMES))
    if frames > CHUNK_FRAMES - 2 * BORDER_FRAMES:
        starts[-1] = frames - (CHUNK_FRAMES - BORDER_FRAMES)
    return starts


def peak_times(logits: np.ndarray) -> np.ndarray:
    """Seconds of local maxima above probability 0.5; adjacent peak frames merge to their mean."""
    from scipy.ndimage import maximum_filter1d

    peaks = np.flatnonzero((logits > 0.0) & (logits == maximum_filter1d(
        logits, PEAK_WINDOW_FRAMES, mode="constant", cval=-1000.0)))
    groups = np.split(peaks, np.flatnonzero(np.diff(peaks) > 1) + 1) if len(peaks) else []
    return np.array([group.mean() for group in groups], dtype=float) / FPS


def beats_from_logits(beat_logits: np.ndarray, downbeat_logits: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    beats, downbeats = peak_times(beat_logits), peak_times(downbeat_logits)
    if len(beats) and len(downbeats):  # every downbeat sits on its nearest beat
        downbeats = np.unique(beats[np.abs(beats[None, :] - downbeats[:, None]).argmin(axis=1)])
    return beats, downbeats


class OnnxAudio2Beats:
    """``(signal, sample_rate) -> (beats, downbeats)`` like beat_this's Audio2Beats(dbn=False)."""

    def __init__(self, path: Path) -> None:
        import onnxruntime

        options = onnxruntime.SessionOptions()
        # Half the cores: analysis runs while the user keeps editing/previewing.
        options.intra_op_num_threads = max(1, (os.cpu_count() or 2) // 2)
        self._session = onnxruntime.InferenceSession(str(path), options, providers=["CPUExecutionProvider"])

    def __call__(self, signal: np.ndarray, sample_rate: int) -> tuple[np.ndarray, np.ndarray]:
        if sample_rate != SAMPLE_RATE:
            raise ValueError(f"Beat This expects {SAMPLE_RATE} Hz audio, got {sample_rate}")
        spect = log_mel(np.asarray(signal, dtype=np.float32))
        frames = len(spect)
        beat = np.full(frames, -1000.0, dtype=np.float32)
        downbeat = np.full(frames, -1000.0, dtype=np.float32)
        for start in reversed(chunk_starts(frames)):  # earlier chunks win their overlap
            # Zero borders only past the piece's edges; a piece under one chunk stays short.
            chunk = spect[max(start, 0):start + CHUNK_FRAMES]
            left = max(0, -start)
            right = max(0, min(BORDER_FRAMES, start + CHUNK_FRAMES - frames))
            chunk = np.pad(chunk, ((left, right), (0, 0)))
            beat_chunk, downbeat_chunk = self._session.run(None, {"spect": chunk[None]})
            low, high = start + BORDER_FRAMES, min(start + CHUNK_FRAMES - BORDER_FRAMES, frames)
            beat[low:high] = beat_chunk[0, BORDER_FRAMES:BORDER_FRAMES + high - low]
            downbeat[low:high] = downbeat_chunk[0, BORDER_FRAMES:BORDER_FRAMES + high - low]
        return beats_from_logits(beat, downbeat)


class BeatThisOnnxAnalysisProvider(BeatThisAnalysisProvider):
    """BeatThisAnalysisProvider with the network run by ONNX Runtime, and
    Open-Unmix (also ONNX) instead of Demucs for vocal activity."""

    provider_id = "beat_this_onnx"
    ONNX_VERSION = "3"
    """2: the basic analyzer's version 6 fields (decay start). 3: vocal_coverage."""

    def __init__(self, ffmpeg_executable: Path) -> None:
        super().__init__(ffmpeg_executable)
        self.version = f"{self.ONNX_VERSION}+{Path(MODEL_NAME).stem}+ort{_installed_onnxruntime_version()}"
        self._vocals = None
        if model_path(ONNX_MODEL_NAME).is_file():
            self._vocals = OnnxVocalDetector(self._basic._decode_mono_pcm, model_path(ONNX_MODEL_NAME))
            self.version += f"+vox-{ONNX_ENGINE_ID}"

    def _load_model(self):
        with self._model_lock:
            if self._model is None:
                self._model = OnnxAudio2Beats(model_path())
            return self._model


def _installed_onnxruntime_version() -> str:
    try:
        from importlib.metadata import version

        return version("onnxruntime")
    except Exception:  # noqa: BLE001 - a version string must never block construction
        return "unavailable"
